name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: Build and Release
        run: |
          cd android	 
          chmod a+x gradlew
          ./gradlew build
          ./gradlew assembleRelease
          ./gradlew app:bundleRelease
        env:
          STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.STORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.STORE_PASSWORD }}
    - name: "upload apk to App Center"
        uses: wzieba/AppCenter-Github-Action@v1
        with:
          appName: "jeyapriya@vthink.co.in/React-App"
          token: ${{secrets.APP_CENTER_TOKEN}}
          file: ./android/app/build/outputs/apk/release/app-release.apk
          group: "tester" 
          notifyTesters: "true"
